# Generated by Django 3.1.2 on 2021-10-16 20:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.BigIntegerField()),
                ('gid2', models.BigIntegerField()),
                ('comune_bel', models.CharField(max_length=254)),
                ('avdicm', models.CharField(max_length=254)),
                ('classid', models.CharField(max_length=254)),
                ('comune_ist', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_lo', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('geom_md', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('geom_hi', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Border',
                'verbose_name_plural': 'Borders',
                'ordering': ('name',),
            },
        ),
    ]
